### ISSUE TITLE
Траблы - Json

### ISSUE THREAD

**Issue by jorjik** [DivanDesign/MODXEvo.snippet.ddGetMultipleField#2]
Делаю плейлист для плеера; получаю

http:\/\/www.jplayer.org\/audio\/mp3\/TSP-01-Cro_magnon_man.mp3
** и везде квадратные скобки; а нужно:
    [
      		{ title:"Cro Magnon Man",
      			mp3:"http://www.jplayer.org/audio/mp3/TSP-01-Cro_magnon_man.mp3"
      		},
      		{ title:"Your Face",
      			mp3:"http://www.jplayer.org/audio/mp3/TSP-05-Your_face.mp3"
      		},
      		{ title:"Cyber Sonnet",
      			mp3:"http://www.jplayer.org/audio/mp3/TSP-07-Cybersonnet.mp3"
      		}
      	]
вызов:
[[ddGetMultipleField?	
	&docField=`file`
	&docId=`4`
	&rowTpl=`mp3.tpl`
	&outputFormat=`JSON`
	&rowGlue=`,`
]]
** плюс не понял, что даёт "array/htmlarray" ?

**Comment by Ronef** [comment]
По описанию трудно понять проблему, но я попытаюсь.
1. При `outputFormat` == 'json' `rowTpl` не используется, это просто двумерный массив (_массив массивов_) в формате JSON (массив объектов не возможен, т.к. сниппету негде взять информацию о ключе колонки).
2. Если вам нужен JSON в виде массива объектов, то используйте `rowTpl`, `rowGlue` и `outerTpl`:
```
[[ddGetMultipleField?
	&docField=`file`
	&docId=`4`
	&outerTpl=`mp3`
	&rowTpl=`mp3_item`
	&rowGlue=`,`
]]
```
Код чанка `mp3`:
```
[ [+result+] ]
```
Код чанка `mp3_item`:
```
{"title": "[+col0+]", "mp3": "[+col1+]"}
```

**Comment by Ronef** [comment]
«array» и  «htmlarray» имеют смысл только вместе с параметром `resultToPlaceholder`.
