### ISSUE TITLE
Путь к библиотеке ddtools

### ISSUE THREAD

**Issue by MrSwed** [DivanDesign/MODXEvo.snippet.ddGetMultipleField#6]
Как вы смотрите на то что бы добавить параметр для указания пути к библиотеке?
А также сделать его по умолчанию, указывающим на уже установленную по умолчанию в MM 
assets/plugins/managermanager/modx.ddtools.class.php, тем самым избежать дублирования библиотеки и сократить время на установку сниппета?

**Comment by Ronef** [comment]
В MM скорее всего используется другая версия. А для того, чтобы упростить установку сниппета, надо добавить библиотеку ddTools в сборку MODX по умолчанию =)
