### ISSUE TITLE
Modifiers usage in item chunk?

### ISSUE THREAD

**Issue by sashabeep** [DivanDesign/MODXEvo.snippet.ddGetMultipleField#8]
1.3.3 and up - new modifiers syntax
Call:

```
[[ddgetmultiplefield?
&inputString_docField=`photos`
&rowTpl=`rowTpl`
]]
```

rowTpl chunk:
```
[+col1:isNot(``):then(`<div class="banner"><a href="[+col1+]"><img src="[+col0+]" alt=""></a></div>`)+]

<@IF:[+col1:isNot('')+]>
	COL1 is not empty!
<@ENDIF>
	
<@IF:[+col1:isntEmpty+]>
	COL1 is not empty! using isntEmpty
<@ENDIF>
```

no one of this conditions works in 1.3.6, 1.4 RC1 in ddgetmultiplefield item chunk.
Of course, if i use just [+col0+] and [+col1+] without conditions column showed as needed.
OR [[if? &is=`[+col1+]:not:` &then=`COL1 is not empty! using IF`]] - works as expected

**Comment by sashabeep** [comment]
Maybe, ddgetmultiplefield placeholders parsing is not system-like, but it's strange that IF snipped worked

**Comment by Tornek** [comment]
Evolution CMS has problem with <@IF> - syntax. Maybe this feature will be removed in the next version CMS.
I recommend using the snippet «if» or «ddIf».
